[server]
enableAccessInterceptor = true
enableAccessInterceptorRes = true
port = 9001

[store]
type = "sqlite"
enableExpireJob = true
expireJobInterval = "5s"

# [leveldb]
# path = "~/workspace/public/aichatoffice/aichatoffice/leveldb"

[sqlite]
path = "~/workspace/public/aichatoffice/aichatoffice/sqlite"


[host]
downloadUrlPrefix = "http://127.0.0.1:9001"
previewUrlPrefix = "http://127.0.0.1:9101"

[case]
resourcePath = "./resource"


[userChat]
reset = ["/reset"]
timeout = 300
# conversationLimit = 5
convertedTextDir = "converted"

# baseUrl = "https://api.deepseek.com/v1"
# textModel = "deepseek-chat"
# token = "sk-a35b80c0627c49f49bbbaf9a1e3e70e2"

[openai]
aiIcon = "https://cdn-icons-png.flaticon.com/512/5278/5278402.png"
[[openai.llm]]
baseUrl = "https://api.siliconflow.cn/v1"
textModel = "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
token = "sk-xisjdsqkpwdypklaubsigiewuoxrkctrfynieiqwgxfetgtz"
name = "硅基流动-Deepseek"
proxyUrl = ""
subservice = ""
inputMaxToken = 10000
outputMaxToken = 10000
[[openai.llm]]
baseUrl = "https://xiaoai.plus/v1"
textModel = "deepseek-v3"
token = "sk-an0ttsr7hLww289uEaK819A57MnUkflvFXeBAvjUhHc0Pxwq"
name = "小爱-Deepseek"
proxyUrl = ""
subservice = ""
inputMaxToken = 10000
outputMaxToken = 10000
[[openai.llm]]
baseUrl = "https://xiaoai.plus/v1"
textModel = "gpt-4-32k"
token = "sk-an0ttsr7hLww289uEaK819A57MnUkflvFXeBAvjUhHc0Pxwq"
name = "小爱-GPT"
proxyUrl = ""
subservice = ""
inputMaxToken = 10000
outputMaxToken = 10000
