[server]
enableAccessInterceptor = true
enableAccessInterceptorRes = true
port = 9001

[store]
type = "sqlite"
enableExpireJob = true
expireJobInterval = "5s"

# [leveldb]
# path = "~/workspace/public/aichatoffice/aichatoffice/leveldb"

[sqlite]
path = "~/workspace/public/aichatoffice/aichatoffice/sqlite"


[host]
downloadUrlPrefix = "http://127.0.0.1:9001"
previewUrlPrefix = "http://127.0.0.1:9101"

[case]
resourcePath = "./resource"


[userChat]
reset = ["/reset"]
timeout = 300
# conversationLimit = 5
convertedTextDir = "converted"

[openai]
aiIcon = "https://cdn-icons-png.flaticon.com/512/5278/5278402.png"
